# Importing and Loading Data

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat

In [6]:
data = loadmat('c2p3.mat')
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: LNX86, Created on: Fri Feb 23 04:10:19 2001',
 '__version__': '1.0',
 '__globals__': [],
 'counts': array([[0],
        [0],
        [1],
        ...,
        [1],
        [0],
        [1]], shape=(32767, 1), dtype=uint8),
 'stim': array([[[ 1,  1,  1, ..., -1,  1, -1],
         [ 1, -1, -1, ...,  1,  1, -1],
         [-1,  1,  1, ..., -1,  1,  1],
         ...,
         [ 1, -1, -1, ..., -1,  1, -1],
         [-1,  1,  1, ...,  1, -1, -1],
         [ 1, -1, -1, ...,  1,  1,  1]],
 
        [[ 1,  1,  1, ..., -1, -1, -1],
         [-1, -1,  1, ...,  1,  1,  1],
         [-1,  1, -1, ...,  1, -1,  1],
         ...,
         [-1, -1, -1, ...,  1, -1,  1],
         [ 1,  1, -1, ...,  1,  1, -1],
         [-1, -1,  1, ..., -1,  1, -1]],
 
        [[-1,  1,  1, ...,  1, -1, -1],
         [-1, -1, -1, ...,  1,  1, -1],
         [ 1,  1, -1, ..., -1, -1,  1],
         ...,
         [-1, -1, -1, ...,  1,  1,  1],
         [ 1, -1, -1, ...,  1, -1

In [7]:
counts = data['counts'].squeeze()     # shape: (num_time_bins,)
stim = data['stim']                   # shape: (16, 16, num_time_bins)

In [9]:
counts

array([0, 0, 1, ..., 1, 0, 1], shape=(32767,), dtype=uint8)

In [10]:
stim

array([[[ 1,  1,  1, ..., -1,  1, -1],
        [ 1, -1, -1, ...,  1,  1, -1],
        [-1,  1,  1, ..., -1,  1,  1],
        ...,
        [ 1, -1, -1, ..., -1,  1, -1],
        [-1,  1,  1, ...,  1, -1, -1],
        [ 1, -1, -1, ...,  1,  1,  1]],

       [[ 1,  1,  1, ..., -1, -1, -1],
        [-1, -1,  1, ...,  1,  1,  1],
        [-1,  1, -1, ...,  1, -1,  1],
        ...,
        [-1, -1, -1, ...,  1, -1,  1],
        [ 1,  1, -1, ...,  1,  1, -1],
        [-1, -1,  1, ..., -1,  1, -1]],

       [[-1,  1,  1, ...,  1, -1, -1],
        [-1, -1, -1, ...,  1,  1, -1],
        [ 1,  1, -1, ..., -1, -1,  1],
        ...,
        [-1, -1, -1, ...,  1,  1,  1],
        [ 1, -1, -1, ...,  1, -1,  1],
        [ 1,  1, -1, ...,  1,  1, -1]],

       ...,

       [[-1, -1, -1, ...,  1, -1, -1],
        [ 1,  1, -1, ..., -1, -1, -1],
        [-1, -1,  1, ..., -1,  1,  1],
        ...,
        [-1,  1,  1, ..., -1,  1, -1],
        [ 1,  1, -1, ...,  1,  1,  1],
        [ 1, -1,  1, ...,  1, -1

In [11]:
print("counts shape:", counts.shape)
print("stim shape:", stim.shape)

counts shape: (32767,)
stim shape: (16, 16, 32767)


In [12]:
stim = np.array(stim)

In [13]:
stim

array([[[ 1,  1,  1, ..., -1,  1, -1],
        [ 1, -1, -1, ...,  1,  1, -1],
        [-1,  1,  1, ..., -1,  1,  1],
        ...,
        [ 1, -1, -1, ..., -1,  1, -1],
        [-1,  1,  1, ...,  1, -1, -1],
        [ 1, -1, -1, ...,  1,  1,  1]],

       [[ 1,  1,  1, ..., -1, -1, -1],
        [-1, -1,  1, ...,  1,  1,  1],
        [-1,  1, -1, ...,  1, -1,  1],
        ...,
        [-1, -1, -1, ...,  1, -1,  1],
        [ 1,  1, -1, ...,  1,  1, -1],
        [-1, -1,  1, ..., -1,  1, -1]],

       [[-1,  1,  1, ...,  1, -1, -1],
        [-1, -1, -1, ...,  1,  1, -1],
        [ 1,  1, -1, ..., -1, -1,  1],
        ...,
        [-1, -1, -1, ...,  1,  1,  1],
        [ 1, -1, -1, ...,  1, -1,  1],
        [ 1,  1, -1, ...,  1,  1, -1]],

       ...,

       [[-1, -1, -1, ...,  1, -1, -1],
        [ 1,  1, -1, ..., -1, -1, -1],
        [-1, -1,  1, ..., -1,  1,  1],
        ...,
        [-1,  1,  1, ..., -1,  1, -1],
        [ 1,  1, -1, ...,  1,  1,  1],
        [ 1, -1,  1, ...,  1, -1

## Solve Tasks below